language: objective-c
sudo: false
osx_image: xcode7.3

cache: bundler

rvm:
  - 2.2.5

install:
  - bundle install
  - npm install -g appium

before_script:
  - appium --log-level warn &

script:
  - bundle exec rake rubocop
  - cd ios_tests; rake ios

notifications:
  email:
    on_success: never
    on_failure: never
